spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "Iv23liCDmDfGxPnzISgo"
            clientSecret: "3262fc76125e572779d1c98018f953d88348867b"
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user